name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    uses: ./.github/workflows/analyze.yml

  test:
    uses: ./.github/workflows/test.yml
    needs: analyze

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/release.yml
    needs: [analyze, test]

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/publish.yml
    needs: [analyze, test]
